# Generated by Django 5.1.4 on 2024-12-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programming_language/')),
                ('video', models.FileField(blank=True, null=True, upload_to='programming_language/')),
                ('level', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20)),
            ],
        ),
    ]
