# Generated by Django 5.1.4 on 2024-12-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/programming_language/'),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/programming_language/'),
        ),
    ]
