# Generated by Django 5.1.4 on 2025-01-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0003_programmerexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmerexpertise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/programmer_expertise'),
        ),
    ]
