# Generated by Django 5.1.4 on 2025-01-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0004_programmerexpertise_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmerexpertise',
            name='image',
        ),
        migrations.AddField(
            model_name='programmerskill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/programmer_skill'),
        ),
    ]
