# Generated by Django 5.1.4 on 2024-12-26 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programming_language', '0003_programmerexpertise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPeoject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_class', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='عمومی', max_length=50)),
                ('educational_heading', models.TextField()),
                ('educational_heading_file', models.FileField(upload_to='static/project/files')),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('buffer_date', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expertise', to='programming_language.programmerexpertise')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_language', to='programming_language.programminglanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
