# Generated by Django 5.1.4 on 2024-12-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0003_programmerexpertise'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationpeoject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/project/image_project'),
        ),
        migrations.RemoveField(
            model_name='educationpeoject',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='educationpeoject',
            name='language',
        ),
        migrations.AddField(
            model_name='educationpeoject',
            name='expertise',
            field=models.ManyToManyField(related_name='project_expertise', to='programming_language.programmerexpertise'),
        ),
        migrations.AddField(
            model_name='educationpeoject',
            name='language',
            field=models.ManyToManyField(related_name='project_language', to='programming_language.programminglanguage'),
        ),
    ]
