# Generated by Django 5.1.4 on 2024-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_educationpeoject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpeoject',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationpeoject',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
