# Generated by Django 5.1.4 on 2024-12-26 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_educationpeoject_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationpeoject',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationpeoject',
            name='educational_heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
