# Generated by Django 5.1.4 on 2024-12-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_educationpeoject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationpeoject',
            name='class_session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
