# Generated by Django 5.1.3 on 2024-12-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='open_status',
            field=models.BooleanField(default=False),
        ),
    ]
