export const data = [
  {
    id: 1,
    name: "علیرضا یوسف نژاد",
    image: "/images/slider/user/user_1.webp",
    banner: "/images/slider/poster/OIP.jpeg",
    email: "aliyousefnazhad@gmail.com",
    score: 5,
    user_expertise: ["Full-Stack Developer"],
    subject: "آموزش پایتون",
    description:
      "در این دوره، علیرضا یوسف نژاد شما را با اصول و مفاهیم پایه و پیشرفته زبان برنامه‌نویسی پایتون آشنا می‌کند. دوره‌ای عملی و کاربردی برای تمامی سطوح برنامه‌نویسی.",
    start_at: "1403/11/06",
    end_at: "1403/11/06",
    time: 60,
    price: 0,
    is_free: true,
    status: "active",
    is_instant: false,
  },
  {
    id: 2,
    name: "مینا کریمی",
    image: "/images/slider/user/user_1.webp",
    banner: "/images/slider/poster/python.jpeg",
    email: "mina.karimi@gmail.com",
    score: 4.8,
    user_expertise: ["UI/UX Designer", "Graphic Artist"],
    subject: "طراحی رابط کاربری مدرن",
    description:
      "مینا کریمی با تجربه‌ای غنی در طراحی، اصول و ابزارهای لازم برای طراحی رابط کاربری جذاب و حرفه‌ای را به شما آموزش خواهد داد.",
    start_at: "1403/11/15",
    end_at: "1403/11/06",
    time: 60,
    price: 500000,
    is_free: false,
    status: "active",
    is_instant: true,
  },
  {
    id: 3,
    name: "سعید محمدی",
    image: "/images/slider/user/user_1.webp",
    banner: "/images/slider/poster/python.jpeg",
    email: "saeed.mohammadi@gmail.com",
    score: 4.9,
    user_expertise: ["Data Scientist", "Machine Learning Engineer"],
    subject: "آموزش یادگیری ماشین",
    description:
      "این دوره با تدریس سعید محمدی، شما را با مفاهیم پایه‌ای و عملی یادگیری ماشین آشنا می‌کند و شما را برای پروژه‌های واقعی آماده می‌سازد.",
    start_at: "1403/11/20",
    end_at: "1403/11/06",
    time: 60,
    price: 500000,
    is_free: false,
    status: "active",
    is_instant: false,
  },
  {
    id: 4,
    name: "فاطمه شریفی",
    image: "/images/slider/user/user_2.png",
    banner: "/images/slider/poster/python.jpeg",
    email: "fatemeh.sharifi@gmail.com",
    score: 4.7,
    user_expertise: ["Digital Marketer", "SEO Specialist"],
    subject: "دیجیتال مارکتینگ برای کسب‌وکارها",
    description:
      "فاطمه شریفی به شما یاد می‌دهد چگونه با استفاده از ابزارهای دیجیتال مارکتینگ، کسب‌وکار خود را گسترش دهید و مشتریان بیشتری جذب کنید.",
    start_at: "1403/11/25",
    end_at: "1403/11/06",
    time: 60,
    price: 500000,
    is_free: false,
    status: "active",
    is_instant: true,
  },
  {
    id: 5,
    name: "حسین رضایی",
    image: "/images/slider/user/user_2.png",
    banner: "/images/slider/poster/python.jpeg",
    email: "hossein.rezaei@gmail.com",
    score: 5,
    user_expertise: ["Cloud Architect", "DevOps Engineer"],
    subject: "مبانی معماری ابری و DevOps",
    description:
      "حسین رضایی شما را با مفاهیم پایه و عملی معماری ابری و مدیریت DevOps آشنا خواهد کرد. مناسب برای توسعه‌دهندگانی که به دنبال ارتقای مهارت‌های حرفه‌ای خود هستند.",
    start_at: "1403/12/01",
    end_at: "1403/11/06",
    time: 60,
    price: 500000,
    is_free: false,
    status: "active",
    is_instant: true,
  },
];
