# Generated by Django 5.1.4 on 2025-01-01 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('close_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('chat', 'Chat'), ('voice_call', 'Voice Call'), ('video_call', 'Video Call')], default='chat', max_length=100)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult', to=settings.AUTH_USER_MODEL)),
                ('consult_applicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_applicator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebugSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('close_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('debuger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debuger', to=settings.AUTH_USER_MODEL)),
                ('debuger_applicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debuger_applicator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
