# Generated by Django 5.1.4 on 2025-01-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugsession',
            name='mode',
            field=models.CharField(choices=[('chat', 'Chat'), ('voice_call', 'Voice Call'), ('video_call', 'Video Call')], default='chat', max_length=100),
        ),
    ]
