# Generated by Django 5.1.4 on 2025-01-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0002_debugsession_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/debug/file'),
        ),
    ]
