# Generated by Django 5.1.4 on 2025-01-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0003_debugsession_description_debugsession_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugsession',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
