# Generated by Django 5.1.4 on 2025-01-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0004_debugsession_start_at_alter_debugsession_close_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugsession',
            name='price',
            field=models.IntegerField(),
        ),
    ]
