# Generated by Django 5.1.4 on 2025-01-02 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0005_alter_debugsession_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugsession',
            name='time',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(20)]),
        ),
    ]
