# Generated by Django 5.1.4 on 2024-12-22 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_role_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
