# Generated by Django 5.1.4 on 2024-12-22 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_remove_role_users_role_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
