# Generated by Django 5.1.4 on 2024-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_role_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
