# Generated by Django 5.1.4 on 2024-12-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='intro_completed',
            field=models.BooleanField(default=False),
        ),
    ]
