# Generated by Django 5.1.4 on 2025-01-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0009_customuser_digital_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='debugger_bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
