# Generated by Django 5.1.4 on 2025-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_customuser_debugger_bio_customuser_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
