# Generated by Django 5.1.4 on 2025-01-02 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0012_alter_customuser_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5, 'امتیاز نمیتواند بیشتر از 5 باشد')]),
        ),
    ]
