# Generated by Django 5.1.4 on 2024-12-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdegree',
            name='degree_file',
            field=models.FileField(blank=True, null=True, upload_to='static/resume/degree_resume'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='static/resume/cv_resume'),
        ),
        migrations.AlterField(
            model_name='videoresume',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/resume/video_resume'),
        ),
        migrations.AlterField(
            model_name='videoresume',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='static/resume/video_resume'),
        ),
    ]
