# Generated by Django 5.1.4 on 2024-12-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0004_alter_userexpertise_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexpertise',
            name='user',
        ),
    ]
