# Generated by Django 5.1.4 on 2024-12-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0005_remove_userexpertise_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExpertise',
        ),
    ]
