# Generated by Django 5.1.4 on 2024-12-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0003_programmerexpertise'),
        ('user_resume', '0006_delete_userexpertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise', models.ManyToManyField(blank=True, related_name='user_expertise', to='programming_language.programmerexpertise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
