# Generated by Django 5.1.4 on 2024-12-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0009_alter_userresume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/resume/image_resume'),
        ),
    ]
